# Generated by Django 5.0.4 on 2024-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_mainbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbox',
            name='icons',
            field=models.CharField(default='', max_length=200),
        ),
    ]
