# Generated by Django 5.0.4 on 2024-08-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_mainbox_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbox',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mainbox',
            name='icons',
        ),
        migrations.AddField(
            model_name='mainbox',
            name='image_box',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='mainbox',
            name='one_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mainbox',
            name='two_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
