# Generated by Django 5.0.4 on 2024-08-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_remove_mainbox_description_remove_mainbox_icons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbox',
            name='btnname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainbox',
            name='rdesc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mainbox',
            name='rtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
