# Generated by Django 5.0.4 on 2024-08-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_mainbox_btnname_mainbox_rdesc_mainbox_rtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbox',
            name='rimage_box',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
