# Generated by Django 5.0.4 on 2024-08-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_mainbox_rimage_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbox',
            name='btnname',
        ),
        migrations.RemoveField(
            model_name='mainbox',
            name='rdesc',
        ),
        migrations.RemoveField(
            model_name='mainbox',
            name='rimage_box',
        ),
        migrations.RemoveField(
            model_name='mainbox',
            name='rtitle',
        ),
    ]
