# Generated by Django 5.0.4 on 2024-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_remove_mainbox_btnname_remove_mainbox_rdesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbox',
            name='btnname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
