# Generated by Django 5.0.4 on 2024-08-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0008_mainbox_btnname'),
    ]

    operations = [
        migrations.CreateModel(
            name='difcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
