# Generated by Django 5.0.4 on 2024-08-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('btnname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/img')),
                ('description', models.TextField()),
            ],
        ),
    ]
