# Generated by Django 5.0.4 on 2024-08-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='fertiService',
        ),
    ]
