# Generated by Django 5.0.4 on 2024-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_rename_service_fertiservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertiservice',
            name='btnname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fertiservice',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fertiservice',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='fertiservice',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
