# Generated by Django 5.0.4 on 2024-08-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_alter_fertiservice_btnname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertiservice',
            name='btnname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fertiservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertiservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='fertiservice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
