# Generated by Django 5.0.4 on 2024-08-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_alter_fertiservice_btnname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='endometriosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('btnname', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
